In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import sklearn

In [ ]:
# Import data
dataset = pd.read_csv("TCGA_GBM_LGG_Mutations_all.csv")
df = pd.DataFrame(dataset)
df.head()

sample_id Grade  Gender   Age_at_diagnosis   Race     IDH1         TP53  \
0          1   LGG    Male  51 years 108 days  white  MUTATED  NOT_MUTATED   
1          2   LGG    Male  38 years 261 days  white  MUTATED  NOT_MUTATED   
2          3   LGG    Male   35 years 62 days  white  MUTATED      MUTATED   
3          4   LGG  Female  32 years 283 days  white  MUTATED      MUTATED   
4          5   LGG    Male  31 years 187 days  white  MUTATED      MUTATED   

          ATRX         PTEN         EGFR  ...        FUBP1          RB1  \
0  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  ...      MUTATED  NOT_MUTATED   
1  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  ...  NOT_MUTATED  NOT_MUTATED   
2      MUTATED  NOT_MUTATED  NOT_MUTATED  ...  NOT_MUTATED  NOT_MUTATED   
3      MUTATED  NOT_MUTATED  NOT_MUTATED  ...  NOT_MUTATED  NOT_MUTATED   
4      MUTATED  NOT_MUTATED  NOT_MUTATED  ...  NOT_MUTATED  NOT_MUTATED   

        NOTCH1         BCOR        CSMD3      SMARCA4       GRIN2A  \
0  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
1  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
2  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
3  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
4  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   

          IDH2         FAT4       PDGFRA  
0  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  
1  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  
2  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  
3  NOT_MUTATED      MUTATED  NOT_MUTATED  
4  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  

[5 rows x 25 columns]

In [ ]:
data = pd.read_excel("test.xlsx")
data_test = pd.DataFrame(data)
data_test.head()

sample id Grade  Gender   Age_at_diagnosis   Race     IDH1         TP53  \
0          1   GBM  Female  41 years 116 days  white  MUTATED  NOT_MUTATED   
1          2   GBM  Female  53 years 258 days  white  MUTATED  NOT_MUTATED   
2          3   GBM    Male  34 years 237 days  white  MUTATED      MUTATED   
3          4   GBM  Female  51 years 350 days  white  MUTATED      MUTATED   
4          5   GBM  Female   30 years 32 days  white  MUTATED      MUTATED   

          ATRX         PTEN         EGFR  ...        FUBP1          RB1  \
0  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  ...  NOT_MUTATED  NOT_MUTATED   
1  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  ...  NOT_MUTATED  NOT_MUTATED   
2      MUTATED  NOT_MUTATED  NOT_MUTATED  ...  NOT_MUTATED  NOT_MUTATED   
3  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  ...  NOT_MUTATED  NOT_MUTATED   
4  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  ...  NOT_MUTATED  NOT_MUTATED   

        NOTCH1         BCOR        CSMD3      SMARCA4       GRIN2A  \
0  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
1  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED      MUTATED  NOT_MUTATED   
2  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
3  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
4  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   

          IDH2         FAT4       PDGFRA  
0  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  
1  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  
2  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  
3  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  
4  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  

[5 rows x 25 columns]

In [ ]:
df_concatenated = pd.concat([df, data], axis=0, ignore_index=True)
df_concatenated.shape

(862, 26)

In [ ]:
# Identify missing value

df_concatenated.replace("--", float("NaN"), inplace=True)
df_concatenated.replace("not reported", float("NaN"), inplace=True)
df_concatenated.isnull().sum()

sample_id            16
Grade                 0
Gender                4
Age_at_diagnosis      5
Race                 22
IDH1                  0
TP53                  0
ATRX                  0
PTEN                  0
EGFR                  0
CIC                   0
MUC16                 0
PIK3CA                0
NF1                   0
PIK3R1                0
FUBP1                 0
RB1                   0
NOTCH1                0
BCOR                  0
CSMD3                 0
SMARCA4               0
GRIN2A                0
IDH2                  0
FAT4                  0
PDGFRA                0
sample id           846
dtype: int64

In [ ]:
X = df_concatenated.drop('Grade', axis=1)
X = X.drop('sample_id', axis=1)
X = X.drop('sample id', axis=1)
X.head()

Gender   Age_at_diagnosis   Race     IDH1         TP53         ATRX  \
0    Male  51 years 108 days  white  MUTATED  NOT_MUTATED  NOT_MUTATED   
1    Male  38 years 261 days  white  MUTATED  NOT_MUTATED  NOT_MUTATED   
2    Male   35 years 62 days  white  MUTATED      MUTATED      MUTATED   
3  Female  32 years 283 days  white  MUTATED      MUTATED      MUTATED   
4    Male  31 years 187 days  white  MUTATED      MUTATED      MUTATED   

          PTEN         EGFR          CIC        MUC16  ...        FUBP1  \
0  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  ...      MUTATED   
1  NOT_MUTATED  NOT_MUTATED      MUTATED  NOT_MUTATED  ...  NOT_MUTATED   
2  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  ...  NOT_MUTATED   
3  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED      MUTATED  ...  NOT_MUTATED   
4  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  ...  NOT_MUTATED   

           RB1       NOTCH1         BCOR        CSMD3      SMARCA4  \
0  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
1  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
2  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
3  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
4  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   

        GRIN2A         IDH2         FAT4       PDGFRA  
0  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  
1  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  
2  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  
3  NOT_MUTATED  NOT_MUTATED      MUTATED  NOT_MUTATED  
4  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  

[5 rows x 23 columns]

In [ ]:
Y = df['Grade']
Y.head()

0    LGG
1    LGG
2    LGG
3    LGG
4    LGG
Name: Grade, dtype: object

In [ ]:
# Converte age in days

for i in range(X.shape[0]):
  if not pd.isna(X.iloc[i, 1]):
      parts = X.iloc[i, 1].split(' ')
      years = int(parts[0])
      if len(parts) == 4 :
        days = int(parts[2])
        totalDays = years * 365 + days
      else :
        totalDays = years * 365
      X.iloc[i, 1] = totalDays

X.head()

Gender Age_at_diagnosis   Race     IDH1         TP53         ATRX  \
0    Male            18723  white  MUTATED  NOT_MUTATED  NOT_MUTATED   
1    Male            14131  white  MUTATED  NOT_MUTATED  NOT_MUTATED   
2    Male            12837  white  MUTATED      MUTATED      MUTATED   
3  Female            11963  white  MUTATED      MUTATED      MUTATED   
4    Male            11502  white  MUTATED      MUTATED      MUTATED   

          PTEN         EGFR          CIC        MUC16  ...        FUBP1  \
0  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  ...      MUTATED   
1  NOT_MUTATED  NOT_MUTATED      MUTATED  NOT_MUTATED  ...  NOT_MUTATED   
2  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  ...  NOT_MUTATED   
3  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED      MUTATED  ...  NOT_MUTATED   
4  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  ...  NOT_MUTATED   

           RB1       NOTCH1         BCOR        CSMD3      SMARCA4  \
0  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
1  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
2  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
3  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   
4  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED   

        GRIN2A         IDH2         FAT4       PDGFRA  
0  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  
1  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  
2  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  
3  NOT_MUTATED  NOT_MUTATED      MUTATED  NOT_MUTATED  
4  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  NOT_MUTATED  

[5 rows x 23 columns]

In [ ]:
X = X.values
Y = Y.values

In [ ]:
# Handling the missing values

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer.fit(X)
X = imputer.transform(X)

In [ ]:
for i in range (X.shape[0]):
  for j in range(X.shape[1]):
    if X[i][j]=='Male' or X[i][j]== 'MUTATED' :
      X[i][j] = 1
    if X[i][j]=='Female' or X[i][j]== 'NOT_MUTATED' :
      X[i][j] = 0

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X[0:5])

[[0.0 0.0 0.0 1.0 1 18723 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0]
 [0.0 0.0 0.0 1.0 1 14131 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0.0 0.0 0.0 1.0 1 12837 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0.0 0.0 0.0 1.0 0 11963 1 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0]
 [0.0 0.0 0.0 1.0 1 11502 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)
print(Y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 0 

In [ ]:
test = X[-16:]
test.shape

(16, 26)

In [ ]:
X = X[:846]
X.shape

(846, 26)

In [ ]:
# Splitting dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)

num_classes = 2
input_shape = X.shape[1]

In [ ]:
print(X_train.shape)
print(X_train[:2])
print(X_test.shape)
print(X_test[:2])

(676, 26)
[[0.0 0.0 0.0 1.0 0 26886 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0.0 0.0 0.0 1.0 1 13556 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
(170, 26)
[[0.0 0.0 0.0 1.0 0 23190 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0.0 0.0 0.0 1.0 0 23920 1 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0]]


In [ ]:
print(y_train.shape)
print(y_train)
print(y_test.shape)
print(y_test)

(676,)
[1 1 1 1 0 1 1 0 1 1 0 1 1 0 0 1 0 1 0 1 1 0 0 0 1 1 0 1 0 1 0 0 1 0 1 1 0
 1 1 0 1 0 1 0 1 0 0 0 0 0 1 1 1 0 0 0 0 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 0 0
 0 1 0 1 0 0 0 0 1 0 1 1 1 1 1 1 1 1 0 1 0 0 0 1 0 0 1 1 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 0 1 1 0 1 0 0 0 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 1 1 0
 1 1 0 0 0 1 1 0 0 1 1 1 0 0 0 1 1 1 1 0 1 1 1 1 0 1 0 1 1 1 1 1 0 1 1 0 0
 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 0 1 0 0 1 0 0 0 0 1 0 0 0 0 1 0
 0 1 1 0 0 0 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 0 0 1 1 1 0 1 0 0 0 1 0 0 0 1 1
 0 0 0 0 1 0 0 1 1 0 1 0 0 1 0 0 1 1 1 0 1 0 1 0 1 1 1 1 1 0 1 1 1 1 1 0 1
 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 1 0 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1
 0 0 1 1 0 0 0 0 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 0 1 0 0 1 0 1 0 0 0 1 0 1 1
 0 0 0 1 0 1 0 0 1 1 1 1 0 1 0 1 1 1 0 0 1 0 1 0 0 0 1 1 0 0 0 1 1 1 1 1 0
 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 1 0 0 0 1 0 1 1 1
 0 1 1 0 0 1 0 1 1 1 1 1 1 0 1 0 0 0 0 1 0 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 0
 1 1 1 0 1 1 0 1 0

In [ ]:
from sklearn.preprocessing import StandardScaler
sta = StandardScaler()
X_train[:, 5:6] = sta.fit_transform(X_train[:, 5:6])
X_test[:, 5:6] = sta.transform(X_test[:, 5:6])

In [ ]:
print("Train : ",X_train[:2])
print("Test : ",X_test[:2])

Train :  [[0.0 0.0 0.0 1.0 0 1.4131147588851984 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
  0 0 0]
 [0.0 0.0 0.0 1.0 1 -0.8631469295391618 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0]]
Test :  [[0.0 0.0 0.0 1.0 0 0.7819772344728627 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0]
 [0.0 0.0 0.0 1.0 0 0.9066337260369874 1 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0
  0 0 0]]


In [ ]:
import keras
from keras import layers

In [ ]:
# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

In [ ]:
print(y_train[:5])


[[0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]]


In [ ]:
!pip install keras-tuner --upgrade

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.1/129.1 kB 3.2 MB/s eta 0:00:00


In [ ]:
X_train = X_train.astype('float32')
y_train = y_train.astype('float32')
X_test = X_train.astype('float32')
y_test = y_train.astype('float32')
test = test.astype('float32')

In [ ]:
import keras_tuner as kt

def model_builder(hp):
    input = layers.Input(shape=input_shape)
    x = layers.Dense(hp.Int('units_1', min_value=32, max_value=512, step=32), activation="relu")(input)
    x = layers.Dropout(hp.Float('dropout_1', min_value=0.2, max_value=0.5, step=0.1))(x)
    x = layers.Dense(hp.Int('units_2', min_value=32, max_value=512, step=32), activation="relu")(x)
    x = layers.Dropout(hp.Float('dropout_2', min_value=0.2, max_value=0.5, step=0.1))(x)
    output = layers.Dense(num_classes, activation="softmax")(x)

    model = keras.models.Model(input, output)
    model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
    return model

tuner = kt.RandomSearch(
    model_builder,
    objective='val_loss',
    max_trials=3)

Reloading Tuner from ./untitled_project/tuner0.json


In [ ]:
tuner.search(X_train, y_train, epochs=10, validation_split=0.25)
best_model = tuner.get_best_models()[0]

In [ ]:
best_model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 26)]              0         
                                                                 
 dense (Dense)               (None, 192)               5184      
                                                                 
 dropout (Dropout)           (None, 192)               0         
                                                                 
 dense_1 (Dense)             (None, 512)               98816     
                                                                 
 dropout_1 (Dropout)         (None, 512)               0         
                                                                 
 dense_2 (Dense)             (None, 2)                 1026      
                                                                 
Total params: 105026 (410.26 KB)
Trainable params: 105026 (41

In [ ]:
test_loss, test_accuracy = best_model.evaluate(X_test, y_test)
print("Test Accuracy:", test_accuracy)

22/22 [==============================] - 0s 2ms/step - loss: 0.2801 - accuracy: 0.8846
Test Accuracy: 0.8846153616905212


In [ ]:
best_params = tuner.get_best_hyperparameters()[0].values
print(best_params)

{'units_1': 192, 'dropout_1': 0.30000000000000004, 'units_2': 512, 'dropout_2': 0.30000000000000004}


In [ ]:
test[:, 5:6] = sta.fit_transform(test[:, 5:6])

In [ ]:
predictions = best_model.predict(test)

1/1 [==============================] - 0s 23ms/step


In [ ]:
print(predictions)

[[0.01517773 0.98482233]
 [0.00283802 0.9971619 ]
 [0.04453068 0.95546937]
 [0.08271281 0.91728723]
 [0.03799341 0.96200657]
 [0.84085506 0.15914494]
 [0.04048324 0.9595168 ]
 [0.6400209  0.35997906]
 [0.7071503  0.29284972]
 [0.90257865 0.09742124]
 [0.9892976  0.01070231]
 [0.74769413 0.2523058 ]
 [0.77330834 0.22669156]
 [0.80075765 0.1992424 ]
 [0.84490305 0.15509687]
 [0.9457018  0.05429814]]
